organizations:
- name: organizations/${organization_id}
  iamPolicy:
    bindings:
    - role: roles/orgpolicy.policyAdmin
      members:
      - ${devops_sa}
    - role: roles/resourcemanager.organizationAdmin
      members:
      - ${devops_sa}
    - role: roles/serviceusage.serviceUsageAdmin
      members:
      - ${devops_sa}
folders: []
projects: []