displayName: ${domain}
folders:
- displayName : ${folder_devops}
  projects:
  - displayName: ${project_control}
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - cloudkms.googleapis.com             # - For CMEK keys
    - storage.googleapis.com              # - For storage buckets (terraform state)
    - cloudresourcemanager.googleapis.com # - Required for running terraform
    - serviceusage.googleapis.com         # - Required for running terraform 
    - iam.googleapis.com                  # - Required for running terraform
    - cloudbuild.googleapis.com           # - Required for running terraform
    - cloudasset.googleapis.com           # - Required for running terraform
    - orgpolicy.googleapis.com            # - Required for running terraform
    - pubsub.googleapis.com               # - Required for running terraform
    - bigquery.googleapis.com             # - Required for running terraform
    - bigquerymigration.googleapis.com    # - Enabled by google as dependency
    - bigquerystorage.googleapis.com      # - Enabled by google as dependency
- displayName: ${folder_management}
  projects:
  - displayName: ${project_logging}
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - cloudkms.googleapis.com             # - For CMEK keys
    - bigquery.googleapis.com             # - For logging to bigquery
    - bigquerymigration.googleapis.com    # - Enabled by google as dependency
    - bigquerystorage.googleapis.com      # - Enabled by google as dependency
  - displayName: ${project_billing}
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - bigquery.googleapis.com             # - For billing to bigquery
  - displayName: ${project_guardrails}
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - cloudkms.googleapis.com             # - For CMEK keys
    - storage.googleapis.com              # - For cloud functions
    - artifactregistry.googleapis.com     # - For cloud functions
    - pubsub.googleapis.com               # - For cloud functions
    - cloudbuild.googleapis.com           # - For cloud functions
    - cloudfunctions.googleapis.com       # - For guardrails
