domain: ${domain}
folders:
- display_name : devops
  projects:
  - name: control
    services: 
    - cloudkms.googleapis.com
    - storage.googleapis.com
  - name: pipelines
    services:       
    - serviceusage.googleapis.com
    - cloudkms.googleapis.com
    - storage.googleapis.com
    - artifactregistry.googleapis.com
    - sourcerepo.googleapis.com
    - cloudbuild.googleapis.com
- display_name: management
  projects:
  - name: logging
    services: []
  - name: billing
    services: []
  - name: guardrails
    services: []
  