organizations:
- name: organizations
  iamPolicy:
    bindings:
    - role: roles/resourcemanager.organizationAdmin
      members:
      - devops
      - management
    - role: roles/orgpolicy.policyAdmin
      members:
      - devops
      - management
    - role: roles/serviceusage.serviceUsageAdmin
      members:
      - devops
    - role: roles/iam.serviceAccountAdmin
      members:
      - devops
      - management
    - role: roles/cloudkms.admin
      members:
      - devops
      - management
    - role: roles/artifactregistry.admin
      members:
      - devops
      - management
    - role: roles/storage.admin
      members:
      - devops
      - management
    - role: roles/iam.workloadIdentityPoolAdmin
      members:
      - devops
    - role: roles/cloudasset.viewer
      members:
      - management
    - role: roles/logging.admin
      members:
      - management
    - role: roles/pubsub.admin
      members:
      - management
    - role: roles/bigquery.admin
      members:
      - management
    - role: roles/cloudfunctions.admin
      members:
      - management
    - role: roles/iam.serviceAccountUser
      members:
      - management



folders: []
projects: []