depth: 50
# since: d96913bf1598dae0efc01f895febd1539621401b
no_entropy: True # Enable entropy matching
no_pattern: False
exclude:
  # - path: - ^tests/ # Exclude the 'tests' directory (message: "Exclude the tests directory")
  - message: Trufflehog rules file contains regexes which might trigger the scanner
    paths:
      - .github/trufflehog-action-config.yaml
      - .github/trufflehog-action-rule.yaml
      - .github/.trufflehog-action.config.yaml
      - .github/.trufflehog-action.rule.yaml
  - message: Ignore private Github workaround
    pattern: github.com/XBankGCPOrg".insteadOf